apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zda4y5ws6-python 
  janus-idp.io/tekton: zda4y5ws6-python
  backstage.io/kubernetes-id: zda4y5ws6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zda4y5ws6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml